### PR TITLE
Update to 0.15.0

### PR DESCRIPTION
**Pull request by synapticarbors**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by synapticarbors** [comment]
@conda-forge-admin, please rerender

**Comment by synapticarbors** [comment]
@conda-forge/jsonnet -- I've submitted this PR to update to a current version of the package since it looks like several automatic PRs from the regro bot haven't been acted on. I've also added myself as a co-maintainer. 

Please note that I removed the `build.sh` to simplify things, and it seems to be passing the CI. When you get a chance, please have a look at this.

**Comment by nelson-liu** [comment]
Hi sorry, not sure how I wasn't watching this repo. Thanks for making these changes!

**Comment by synapticarbors** [comment]
@nelson-liu -- The travis stuff I think is a known error with a disk space quota being exceed for the `ppc64le` build. @conda-forge/help-ppc64le -- is this ok to ignore?

**Comment by jayfurmanek** [comment]
yea, there is one node (on Travis) that is showing that error. rekicking the build usually gets past it.
Or, merge and rekick the publish build on Travis, if needed.

**Comment by nelson-liu** [comment]
Thanks for the context, I'll merge this for now. Would be nice to have binaries built for ppc64ie eventually

**Comment by jayfurmanek** [comment]
It looks like the ppc64le publish build succeeded.

**Pull request merged**
